### ISSUE TITLE
Context doesn't load $_SERVER

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Web#28]
The auto-globals-jit directive is turned on by default in the php.ini that ships with PHP 5.5.x (and may be for 5.4.x too). This causes $_SERVER and $_ENV not to be loaded until they are used; thus, they don't show up in $GLOBALS. This can cause a router failure.

**Comment by harikt** [comment]
v1 I assume.

**Comment by harikt** [comment]
@brandonsavage and I am not sure whether you have created the issue in wrong place. Aura.Session you mean ?

**Comment by pmjones** [comment]
Heh, I think he meant $_SERVER.

**Comment by brandonsavage** [comment]
I meant $_SERVER, updated the bug.

**Comment by harikt** [comment]
In travis this is running https://travis-ci.org/auraphp/Aura.Web/builds/11254586 . Not sure why at your end :( .

**Comment by pmjones** [comment]
I can think of no solution that does not introduce superglobals into the internals of class. I would like to avoid such an introduction.

Perhaps a documentation addition is in order here? E.g., "If jit-globals is turned on, pass `compact($_SERVER, $_GET, $_POST, $_COOKIE, $_ENV)` instead of `$GLOBALS`." 

Other thoughts?

**Comment by harikt** [comment]
@pmjones good for me :+1:

**Comment by pmjones** [comment]
@brandonsavage Are we OK with a documentation fix here?

**Comment by brandonsavage** [comment]
If we can't fix it for real, yes.
