### ISSUE TITLE
Why dot infront ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web#3]
Hi @pmjones  , 

I wonder why we want the dot infront of the format .

For eg : `'format' => '.json'` , can we remove it ? So its easy just to put `html` , `xml` etc and the dot by the system itself ?

**Comment by pmjones** [comment]
The primary reason is that in Solar, we had some guys who needed ".0" (i.e., dot-zero) format recognition. There was a ton of checking for empty strings, zeroes, strict-equality, etc. Based on some work with DocBook configuration, I realized that using a dot in front of the extension makes it trivially easy to work with the format, no matter what it is. As another example, it means you can just append the format to the pathinfo, instead of having to check if there's an extension, the concat it with a dot.

**Comment by harikt** [comment]
Not sure so if they need dot zero , then they need to give something like 
`'format' => '0'` , doesn't that works ? Or there is something other than that ?
I don't know more about the dot zero format , so leaving the decision to you :-)

**Comment by pmjones** [comment]
The use of `'format' => '0'` does not work, because then `$values['format'] == false`.  That causes a lot of trouble in that one edge case.  :-)
